-- Create the otp_codes table
CREATE TABLE IF NOT EXISTS public.otp_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile TEXT NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

-- Create the study_shares table
CREATE TABLE IF NOT EXISTS public.study_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_instance_uid TEXT NOT NULL,
  shared_by UUID NOT NULL REFERENCES auth.users(id),
  shared_with UUID REFERENCES auth.users(id),
  patient_name TEXT,
  patient_mobile TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on the study_shares table
ALTER TABLE public.study_shares ENABLE ROW LEVEL SECURITY;

-- RLS policy for users to see studies they have shared
CREATE POLICY "Users can see studies they have shared"
ON public.study_shares
FOR SELECT
USING (auth.uid() = shared_by);

-- RLS policy for users to see studies shared with them
CREATE POLICY "Users can see studies shared with them"
ON public.study_shares
FOR SELECT
USING (auth.uid() = shared_with);

-- RLS policy for users to insert their own shares
CREATE POLICY "Users can insert their own shares"
ON public.study_shares
FOR INSERT
WITH CHECK (auth.uid() = shared_by);

-- Create the onboard_user function
CREATE OR REPLACE FUNCTION onboard_user(
  name TEXT,
  email TEXT,
  mobile TEXT,
  role TEXT,
  created_by UUID
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_user_id UUID;
  user_profile JSON;
BEGIN
  -- Create the user in auth.users
  INSERT INTO auth.users (email, phone, role, instance_id, aud)
  VALUES (email, mobile, 'authenticated', '00000000-0000-0000-0000-000000000000', 'authenticated')
  RETURNING id INTO new_user_id;

  -- Insert into public.profiles
  INSERT INTO public.profiles (id, name, email, mobile, role, created_by)
  VALUES (new_user_id, name, email, mobile, role, created_by);

  -- Send an invitation email
  PERFORM http_post(
    'https://api.supabase.io/v1/auth/admin/invite',
    jsonb_build_object('email', email),
    '{"Authorization": "Bearer YOUR_SERVICE_ROLE_KEY", "apikey": "YOUR_ANON_KEY"}'
  );

  -- Return the new user's profile
  SELECT json_build_object(
    'id', id,
    'name', name,
    'email', email,
    'mobile', mobile,
    'role', role
  )
  INTO user_profile
  FROM public.profiles
  WHERE id = new_user_id;

  RETURN user_profile;
END;
$$;
